[package]
name = "pants"
version = "0.1.0"
authors = ["Daniel Porteous <danielporteous1@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.2"
tera = "0.11"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
structopt = "0.3"

[dependencies.rocket_contrib]
version = "0.4.2"
default-features = false
features = ["tera_templates"]
